// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren

// unhandled import: ButtonProps from "@fluentui/react-button" 
// unhandled import: ButtonSlots from "@fluentui/react-button" 
// unhandled import: ButtonState from "@fluentui/react-button" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * BreadcrumbButton Props
 */

sealed external interface BreadcrumbButtonProps : BreadcrumbProps, ButtonProps, PropsWithChildren {
    /**
     * Defines current state of BreadcrumbButton.
     *
     * @default false
     */
    var current: Boolean?
}
