// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren

// unhandled import: ButtonProps from "@fluentui/react-button" 
// unhandled import: ButtonSlots from "@fluentui/react-button" 
// unhandled import: ButtonState from "@fluentui/react-button" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * Breadcrumb Props
 */

sealed external interface BreadcrumbProps : BreadcrumbSlots, PropsWithChildren {
    /**
     * Sets the focus behavior for the Breadcrumb.
     *
     * `tab`
     * This behaviour will cycle through all elements inside of the Breadcrumb when pressing the Tab key and then release focus
     * after the last inner element.
     *
     * `arrow`
     * This behaviour will cycle through all elements inside of the Breadcrumb when pressing the Arrow key.
     *
     * @default 'tab'
     */
    var focusMode: (Temp167)?

    /**
     * Controls size of Breadcrumb items and dividers.
     *
     * @default 'medium'
     */
    var size: ButtonSize?
}
