// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ButtonProps from "@fluentui/react-button" 
// unhandled import: ButtonSlots from "@fluentui/react-button" 
// unhandled import: ButtonState from "@fluentui/react-button" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * State used in rendering BreadcrumbDivider
 */

sealed external interface BreadcrumbDividerState : BreadcrumbDividerSlots, BreadcrumbProps
