// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ARIAButtonSlotProps from "@fluentui/react-aria" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


sealed external interface ButtonSlots : SlotPropsRecord {
    /**
     * Root of the component that renders as either a `<button>` tag or an `<a>` tag.
     */
    var root: Slot

    /**
     * Icon that renders either before or after the `children` as specified by the `iconPosition` prop.
     */
    var icon: Slot
}
