// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * Slots available in the CardFooter component.
 */

sealed external interface CardFooterSlots : PropsWithChildren {
    /**
     * Root element of the component.
     */
    var root: Slot

    /**
     * Container that renders on the far end of the footer, used for action buttons.
     */
    var action: Slot
}
