// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * Slots available in the CardHeader component.
 */

sealed external interface CardHeaderSlots {
    /**
     * Root element of the component.
     */
    var root: Slot

    /**
     * Element used to render an image or avatar related to the card.
     */
    var image: Slot

    /**
     * Element used to render the main header title.
     */
    var header: Slot

    /**
     * Element used to render short descriptions related to the title.
     */
    var description: Slot

    /**
     * Container that renders on the far end of the footer, used for action buttons.
     */
    var action: Slot
}
