// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * Slots available in the Card component.
 */

sealed external interface CardPreviewSlots {
    /**
     * Root element of the component.
     */
    var root: Slot

    /**
     * Container that holds a logo related to the image preview provided.
     */
    var logo: Slot
}
