// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * CardPreview component props.
 */
typealias CardPreviewProps = CardPreviewSlots
