// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ActiveDescendantContextValue from "@fluentui/react-aria" 
// unhandled import: ActiveDescendantImperativeRef from "@fluentui/react-aria" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ContextSelector from "@fluentui/react-context-selector" 
// unhandled import: FC from "react" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: PortalProps from "@fluentui/react-portal" 
// unhandled import: PositioningShorthand from "@fluentui/react-positioning" 
// unhandled import: Provider from "react" 
// unhandled import: ProviderProps from "react" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

typealias ComboboxOpenEvents = ComboboxBaseOpenEvents
