// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: DispatchWithoutAction from "react" 

/**
 * Defines the Props type for a component given its slots and the definition of which one is the primary slot,
 * defaulting to root if one is not provided.
 */

external interface ComponentProps<Slots : SlotPropsRecord>
