// Generated by Karakum - do not modify it manually!


package fluentui

import react.FC
import react.ProviderProps


/**
 * @internal
 */

sealed external interface Context<Value> {
    var Provider: FC<ProviderProps<Value>>
    var Consumer: Nothing
}
