// Generated by Karakum - do not modify it manually!


package fluentui

import react.ReactNode


sealed external interface DialogState : DialogSlots, DialogContextValue {
    var content: ReactNode
    var trigger: ReactNode
}
