// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren


/**
 * DialogSurface Props
 */

sealed external interface DialogSurfaceProps : DialogSurfaceSlots, PropsWithChildren
