// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren


sealed external interface DialogTitleSlots : PropsWithChildren {
    /**
     * By default this is a h2, but can be any heading or div,
     * if `div` is provided do not forget to also provide proper `role="heading"` and `aria-level` attributes
     */
    var root: Slot

    /**
     * By default a Dialog with modalType='non-modal' will have a close button action
     */
    var action: Slot
}
