// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren


/**
 * DialogBody Props
 */

sealed external interface DialogBodyProps : DialogBodySlots, PropsWithChildren
