// Generated by Karakum - do not modify it manually!


package fluentui


sealed external interface DialogContextValues {
    var dialog: DialogContextValue

    /**
     * dialogSurface context is provided by Dialog as false
     * to ensure components inside Dialog but outside DialogSurface will consume this as false
     */
    var dialogSurface: DialogSurfaceContextValue
}
