// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren


sealed external interface DialogTriggerProps : DialogTriggerChildProps, PropsWithChildren {
    /**
     * Explicitly declare if the trigger is responsible for opening or
     * closing a Dialog visibility state.
     *
     * If `DialogTrigger` is outside `DialogSurface` then it'll be `open` by default
     *
     * If `DialogTrigger` is inside `DialogSurface` then it'll be `close` by default
     */
    var action: DialogTriggerAction?

    /**
     * Disables internal trigger mechanism that ensures a child provided will be a compliant ARIA button.
     * @default false
     */
    var disableButtonEnhancement: Boolean?
}
