// Generated by Karakum - do not modify it manually!


package fluentui


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface DialogActionsPosition {
    companion object {
        @seskar.js.JsValue("start")
        val start: DialogActionsPosition

        @seskar.js.JsValue("end")
        val end: DialogActionsPosition
    }
}
