// Generated by Karakum - do not modify it manually!


package fluentui

import react.Ref


external interface DialogContextValue : Temp146 {
    var open: Boolean
    var inertTrapFocus: Boolean
    var dialogTitleId: String?
    var isNestedDialog: Boolean
    var dialogRef: Ref<DialogSurfaceElement>
    var modalType: DialogModalType

    /**
     * Requests dialog main component to update it's internal open state
     */
    var requestOpenChange: (data: DialogOpenChangeData) -> Unit
}
