// Generated by Karakum - do not modify it manually!


package fluentui


/**
 * State used in rendering DialogActions
 */

sealed external interface DialogActionsState : DialogActionsSlots, DialogActionsProps
