// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: DialogProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceSlots from "@fluentui/react-dialog" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


sealed external interface DrawerHeaderTitleSlots : PropsWithChildren {
    var root: Slot

    /**
     * By default this is a h2, but can be any heading or div.
     * If `div` is provided do not forget to also provide proper `role="heading"` and `aria-level` attributes
     */
    var heading: Slot

    /**
     * Action slot for the close button
     */
    var action: Slot
}
