// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: DialogProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceSlots from "@fluentui/react-dialog" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


sealed external interface DrawerBaseProps {
    /**
     * Position of the drawer.
     *
     * Note: 'bottom' does not supports size, but it supports customized height.
     *
     * @default 'start'
     */
    var position: (DrawerBasePropsPosition)?

    /**
     * Size of the drawer.
     *
     * - 'small' - Drawer is 320px wide.
     * - 'medium' - Drawer is 592px wide.
     * - 'large' - Drawer is 940px wide.
     * - 'full' - Drawer is 100vw wide.
     *
     * @default 'small'
     */
    var size: (DrawerBasePropsSize)?

    /**
     * Controls the open state of the Drawer
     *
     * @default false
     */
    var open: Boolean?
}
