// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities"
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: CustomStyleHooksContextValue_unstable from "@fluentui/react-shared-contexts" 
// unhandled import: IconDirectionContextValue from "@fluentui/react-icons" 
// unhandled import: OverridesContextValue_unstable from "@fluentui/react-shared-contexts" 
// unhandled import: PartialTheme from "@fluentui/react-theme" 
// unhandled import: ProviderContextValue_unstable from "@fluentui/react-shared-contexts" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 
// unhandled import: Theme from "@fluentui/tokens" 
// unhandled import: ThemeClassNameContextValue_unstable from "@fluentui/react-shared-contexts" 
// unhandled import: ThemeContextValue_unstable from "@fluentui/react-shared-contexts" 
// unhandled import: TooltipVisibilityContextValue_unstable from "@fluentui/react-shared-contexts" 

typealias FluentProviderCustomStyleHooks = JSON
