// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithRef

// unhandled import: DispatchWithoutAction from "react" 

/**
 * Return type for `React.forwardRef`, including inference of the proper typing for the ref.
 */
typealias ForwardRefComponent<Props> = react.ForwardRefExoticComponent<PropsWithRef<Props>>
