// Generated by Karakum - do not modify it manually!

@file:JsModule("@fluentui/react-components")

package fluentui

import react.Provider
import web.html.HTMLLIElement

external val FluentProvider: react.FC<FluentProviderProps>

external val Breadcrumb: react.FC<BreadcrumbProps>

/**
 * A button component which is used inside the Breadcrumb.
 */
external val BreadcrumbButton: react.FC<BreadcrumbButtonProps>

/**
 * Static CSS class names used internally for the component slots.
 */
external val breadcrumbButtonClassNames: SlotClassNames<BreadcrumbButtonSlots>

external val breadcrumbClassNames: SlotClassNames<BreadcrumbSlots>

/**
 * A divider component which is used inside the Breadcrumb
 */
external val BreadcrumbDivider: react.FC<BreadcrumbDividerProps>

external val breadcrumbDividerClassNames: SlotClassNames<BreadcrumbDividerSlots>

/**
 * BreadcrumbItem component is a wrapper for BreadcrumbLink and BreadcrumbButton.
 * It can be used as a non-interactive item.
 */
external val BreadcrumbItem: react.FC<BreadcrumbItemProps>

external val breadcrumbItemClassNames: SlotClassNames<BreadcrumbItemSlots>

/**
 * @internal
 */
external val BreadcrumbProvider: Provider<Required<BreadcrumbProps>?>

external val isTruncatableBreadcrumbContent: (content: String, maxLength: Double) -> Boolean

/**
 * Get the displayed items and overflowing items based on the array of BreadcrumbItems needed for Breadcrumb.
 *
 * @param options - Configure the partition options
 *
 * @returns Three arrays split into displayed items and overflow items based on maxDisplayedItems.
 */
external val partitionBreadcrumbItems: Function<Any?> /* <T>(options: PartitionBreadcrumbItemsOptions<T>) => PartitionBreadcrumbItems<T> */

external val truncateBreadcrumbLongName: (content: String, maxLength: Double? /* use undefined for default */) -> String

external val truncateBreadcrumLongTooltip: (content: String, maxLength: Double? /* use undefined for default */) -> String

/**
 * Apply styling to the BreadcrumbButton slots based on the state
 */
external val useBreadcrumbButtonStyles_unstable: (state: BreadcrumbButtonState) -> BreadcrumbButtonState

/**
 * @internal
 */
external val useBreadcrumbContext_unstable: () -> Required<BreadcrumbProps>

/**
 * Create the state required to render BreadcrumbDivider.
 *
 * The returned state can be modified with hooks such as useBreadcrumbDividerStyles_unstable,
 * before being passed to renderBreadcrumbDivider_unstable.
 *
 * @param props - props from this instance of BreadcrumbDivider
 * @param ref - reference to root HTMLElement of BreadcrumbDivider
 */
external val useBreadcrumbDivider_unstable: (props: BreadcrumbDividerProps, ref: react.Ref<HTMLLIElement>) -> BreadcrumbDividerState

/**
 * Apply styling to the BreadcrumbDivider slots based on the state
 */
external val useBreadcrumbDividerStyles_unstable: (state: BreadcrumbDividerState) -> BreadcrumbDividerState

/**
 * Create the state required to render BreadcrumbItem.
 *
 * The returned state can be modified with hooks such as useBreadcrumbItemStyles_unstable,
 * before being passed to renderBreadcrumbItem_unstable.
 *
 * @param props - props from this instance of BreadcrumbItem
 * @param ref - reference to root HTMLElement of BreadcrumbItem
 */
external val useBreadcrumbItem_unstable: (props: BreadcrumbItemProps, ref: react.Ref<HTMLLIElement>) -> BreadcrumbItemState

/**
 * Apply styling to the BreadcrumbItem slots based on the state
 */
external val useBreadcrumbItemStyles_unstable: (state: BreadcrumbItemState) -> BreadcrumbItemState

/**
 * Apply styling to the Breadcrumb slots based on the state
 */
external val useBreadcrumbStyles_unstable: (state: BreadcrumbState) -> BreadcrumbState

/* export {}; */


/**
 * A card provides scaffolding for hosting actions and content for a single topic.
 */
external val Card: ForwardRefComponent<CardProps>

/**
 * Static CSS class names used internally for the component slots.
 */
external val cardClassNames: SlotClassNames<CardSlots>

/**
 * CSS variable names used internally for uniform styling in Card.
 */
external val cardCSSVars: CardCSSVars

/**
 * Component to render Button actions in a Card component.
 */
external val CardFooter: ForwardRefComponent<CardFooterProps>

/**
 * Static CSS class names used internally for the component slots.
 */
external val cardFooterClassNames: SlotClassNames<CardFooterSlots>

/**
 * Component to render an image, text and an action in a Card component.
 */
external val CardHeader: ForwardRefComponent<CardHeaderProps>

/**
 * Static CSS class names used internally for the component slots.
 */
external val cardHeaderClassNames: SlotClassNames<CardHeaderSlots>

/**
 * CSS variable names used internally for uniform styling in CardHeader.
 */
external val cardHeaderCSSVars: CardHeaderCSSVars

/**
 * Component to render image previews of documents or articles in a Card component.
 */
external val CardPreview: ForwardRefComponent<CardPreviewProps>

/**
 * Static CSS class names used internally for the component slots.
 */
external val cardPreviewClassNames: SlotClassNames<CardPreviewSlots>

/**
 * @internal
 */
external val CardProvider: Provider<CardContextValue?>

/* export {}; */


/* export { __css }; */

/* export { __resetCSS }; */

/* export { __resetStyles }; */

/* export { __styles }; */

/* export { Accordion }; */

/* export { accordionClassNames }; */

/* export { AccordionContextValue }; */

/* export { AccordionContextValues }; */

/* export { AccordionHeader }; */

/* export { accordionHeaderClassNames }; */

/* export { AccordionHeaderContextValue }; */

/* export { AccordionHeaderContextValues }; */

/* export { AccordionHeaderExpandIconPosition }; */

/* export { AccordionHeaderProps }; */

/* export { AccordionHeaderSize }; */

/* export { AccordionHeaderSlots }; */

/* export { AccordionHeaderState }; */

/* export { AccordionIndex }; */

/* export { AccordionItem }; */

/* export { accordionItemClassNames }; */

/* export { AccordionItemContextValue }; */

/* export { AccordionItemContextValues }; */

/* export { AccordionItemProps }; */

/* export { AccordionItemProvider }; */

/* export { AccordionItemSlots }; */

/* export { AccordionItemState }; */

/* export { AccordionItemValue }; */

/* export { AccordionPanel }; */

/* export { accordionPanelClassNames }; */

/* export { AccordionPanelProps }; */

/* export { AccordionPanelSlots }; */

/* export { AccordionPanelState }; */

/* export { AccordionProps }; */

/* export { AccordionProvider }; */

/* export { AccordionSlots }; */

/* export { AccordionState }; */

/* export { AccordionToggleData }; */

/* export { AccordionToggleEvent }; */

/* export { AccordionToggleEventHandler }; */

/* export { AnnounceContextValue }; */

/* export { AnnounceProvider }; */

/* export { AriaLiveAnnouncer }; */

/* export { AriaLiveAnnouncerProps }; */

/* export { AriaLiveAnnouncerState }; */

/* export { arrowHeights }; */

/* export { assertSlots }; */

/* export { Avatar }; */

/* export { avatarClassNames }; */

/* export { AvatarGroup }; */

/* export { avatarGroupClassNames }; */

/* export { AvatarGroupContextValue }; */

/* export { AvatarGroupContextValues }; */

/* export { AvatarGroupItem }; */

/* export { avatarGroupItemClassNames }; */

/* export { AvatarGroupItemProps }; */

/* export { AvatarGroupItemSlots }; */

/* export { AvatarGroupItemState }; */

/* export { AvatarGroupPopover }; */

/* export { avatarGroupPopoverClassNames }; */

/* export { AvatarGroupPopoverProps }; */

/* export { AvatarGroupPopoverSlots }; */

/* export { AvatarGroupPopoverState }; */

/* export { AvatarGroupProps }; */

/* export { AvatarGroupProvider }; */

/* export { AvatarGroupSlots }; */

/* export { AvatarGroupState }; */

/* export { AvatarNamedColor }; */

/* export { AvatarProps }; */

/* export { AvatarSize }; */

/* export { AvatarSizes }; */

/* export { AvatarSlots }; */

/* export { AvatarState }; */

/* export { Badge }; */

/* export { badgeClassNames }; */

/* export { BadgeProps }; */

/* export { BadgeSlots }; */

/* export { BadgeState }; */

/* export { Body1 }; */

/* export { body1ClassNames }; */

/* export { Body1Strong }; */

/* export { body1StrongClassNames }; */

/* export { Body1Stronger }; */

/* export { body1StrongerClassNames }; */

/* export { Body2 }; */

/* export { body2ClassNames }; */

/* export { BorderRadiusTokens }; */

/* export { BrandVariants }; */

/* export { Breadcrumb }; */

/* export { BreadcrumbButton }; */

/* export { breadcrumbButtonClassNames }; */

/* export { BreadcrumbButtonProps }; */

/* export { BreadcrumbButtonSlots }; */

/* export { BreadcrumbButtonState }; */

/* export { breadcrumbClassNames }; */

/* export { BreadcrumbContextValues }; */

/* export { BreadcrumbDivider }; */

/* export { breadcrumbDividerClassNames }; */

/* export { BreadcrumbDividerProps }; */

/* export { BreadcrumbDividerSlots }; */

/* export { BreadcrumbDividerState }; */

/* export { BreadcrumbItem }; */

/* export { breadcrumbItemClassNames }; */

/* export { BreadcrumbItemProps }; */

/* export { BreadcrumbItemSlots }; */

/* export { BreadcrumbItemState }; */

/* export { BreadcrumbProps }; */

/* export { BreadcrumbProvider }; */

/* export { BreadcrumbSlots }; */

/* export { BreadcrumbState }; */

/* export { Button }; */

/* export { buttonClassNames }; */

/* export { ButtonProps }; */

/* export { ButtonSlots }; */

/* export { ButtonState }; */

/* export { Caption1 }; */

/* export { caption1ClassNames }; */

/* export { Caption1Strong }; */

/* export { caption1StrongClassNames }; */

/* export { Caption1Stronger }; */

/* export { caption1StrongerClassNames }; */

/* export { Caption2 }; */

/* export { caption2ClassNames }; */

/* export { Caption2Strong }; */

/* export { caption2StrongClassNames }; */

/* export { Card }; */

/* export { cardClassNames }; */

/* export { cardCSSVars }; */

/* export { CardFooter }; */

/* export { cardFooterClassNames }; */

/* export { CardFooterProps }; */

/* export { CardFooterSlots }; */

/* export { CardFooterState }; */

/* export { CardHeader }; */

/* export { cardHeaderClassNames }; */

/* export { cardHeaderCSSVars }; */

/* export { CardHeaderProps }; */

/* export { CardHeaderSlots }; */

/* export { CardHeaderState }; */

/* export { CardPreview }; */

/* export { cardPreviewClassNames }; */

/* export { CardPreviewProps }; */

/* export { CardPreviewSlots }; */

/* export { CardPreviewState }; */

/* export { CardProps }; */

/* export { CardSlots }; */

/* export { CardState }; */

/* export { Checkbox }; */

/* export { checkboxClassNames }; */

/* export { CheckboxOnChangeData }; */

/* export { CheckboxProps }; */

/* export { CheckboxSlots }; */

/* export { CheckboxState }; */

/* export { ColorPaletteTokens }; */

/* export { ColorTokens }; */

/* export { ColumnIdContextProvider }; */

/* export { Combobox }; */

/* export { comboboxClassNames }; */

/* export { ComboboxContextValue }; */

/* export { ComboboxContextValues }; */

/* export { ComboboxOpenChangeData }; */

/* export { ComboboxOpenEvents }; */

/* export { ComboboxProps }; */

/* export { ComboboxProvider }; */

/* export { ComboboxSlots }; */

/* export { ComboboxState }; */

/* export { ComponentProps }; */

/* export { ComponentState }; */

/* export { CompoundButton }; */

/* export { compoundButtonClassNames }; */

/* export { CompoundButtonProps }; */

/* export { CompoundButtonSlots }; */

/* export { CompoundButtonState }; */

/* export { CounterBadge }; */

/* export { counterBadgeClassNames }; */

/* export { CounterBadgeProps }; */

/* export { CounterBadgeState }; */

/* export { createCSSRuleFromTheme }; */

/* export { createCustomFocusIndicatorStyle }; */

/* export { CreateCustomFocusIndicatorStyleOptions }; */

/* export { createDarkTheme }; */

/* export { createDOMRenderer }; */

/* export { createFocusOutlineStyle }; */

/* export { CreateFocusOutlineStyleOptions }; */

/* export { createHighContrastTheme }; */

/* export { createLightTheme }; */

/* export { createTableColumn }; */

/* export { CreateTableColumnOptions }; */

/* export { createTeamsDarkTheme }; */

/* export { CurveTokens }; */

/* export { DATA_OVERFLOW_DIVIDER }; */

/* export { DATA_OVERFLOW_ITEM }; */

/* export { DATA_OVERFLOW_MENU }; */

/* export { DATA_OVERFLOWING }; */

/* export { DataGrid }; */

/* export { DataGridBody }; */

/* export { dataGridBodyClassNames }; */

/* export { DataGridBodyProps }; */

/* export { DataGridBodySlots }; */

/* export { DataGridBodyState }; */

/* export { DataGridCell }; */

/* export { dataGridCellClassNames }; */

/* export { DataGridCellFocusMode }; */

/* export { DataGridCellProps }; */

/* export { DataGridCellSlots }; */

/* export { DataGridCellState }; */

/* export { dataGridClassNames }; */

/* export { DataGridContextProvider }; */

/* export { DataGridContextValue }; */

/* export { DataGridContextValues }; */

/* export { DataGridFocusMode }; */

/* export { DataGridHeader }; */

/* export { DataGridHeaderCell }; */

/* export { dataGridHeaderCellClassNames }; */

/* export { DataGridHeaderCellProps }; */

/* export { DataGridHeaderCellSlots }; */

/* export { DataGridHeaderCellState }; */

/* export { dataGridHeaderClassNames }; */

/* export { DataGridHeaderProps }; */

/* export { DataGridHeaderSlots }; */

/* export { DataGridHeaderState }; */

/* export { DataGridProps }; */

/* export { DataGridRow }; */

/* export { dataGridRowClassNames }; */

/* export { DataGridRowProps }; */

/* export { DataGridRowSlots }; */

/* export { DataGridRowState }; */

/* export { DataGridSelectionCell }; */

/* export { dataGridSelectionCellClassNames }; */

/* export { DataGridSelectionCellProps }; */

/* export { DataGridSelectionCellSlots }; */

/* export { DataGridSelectionCellState }; */

/* export { DataGridSlots }; */

/* export { DataGridState }; */

/* export { Dialog }; */

/* export { DialogActions }; */

/* export { dialogActionsClassNames }; */

/* export { DialogActionsPosition }; */

/* export { DialogActionsProps }; */

/* export { DialogActionsSlots }; */

/* export { DialogActionsState }; */

/* export { DialogBody }; */

/* export { dialogBodyClassNames }; */

/* export { DialogBodyProps }; */

/* export { DialogBodySlots }; */

/* export { DialogBodyState }; */

/* export { DialogContent }; */

/* export { dialogContentClassNames }; */

/* export { DialogContentProps }; */

/* export { DialogContentSlots }; */

/* export { DialogContentState }; */

/* export { DialogContextValue }; */

/* export { DialogOpenChangeData }; */

/* export { DialogOpenChangeEvent }; */

/* export { DialogProps }; */

/* export { DialogSlots }; */

/* export { DialogState }; */

/* export { DialogSurface }; */

/* export { dialogSurfaceClassNames }; */

/* export { DialogSurfaceContextValue }; */

/* export { DialogSurfaceContextValues }; */

/* export { DialogSurfaceProps }; */

/* export { DialogSurfaceSlots }; */

/* export { DialogSurfaceState }; */

/* export { DialogTitle }; */

/* export { dialogTitleClassNames }; */

/* export { DialogTitleProps }; */

/* export { DialogTitleSlots }; */

/* export { DialogTitleState }; */

/* export { DialogTrigger }; */

/* export { DialogTriggerAction }; */

/* export { DialogTriggerChildProps }; */

/* export { DialogTriggerProps }; */

/* export { DialogTriggerState }; */

/* export { Display }; */

/* export { displayClassNames }; */

/* export { Divider }; */

/* export { dividerClassNames }; */

/* export { DividerProps }; */

/* export { DividerSlots }; */

/* export { DividerState }; */

/* export { Drawer }; */

/* export { DrawerBody }; */

/* export { drawerBodyClassNames }; */

/* export { DrawerBodyProps }; */

/* export { DrawerBodySlots }; */

/* export { DrawerBodyState }; */

/* export { DrawerFooter }; */

/* export { drawerFooterClassNames }; */

/* export { DrawerFooterProps }; */

/* export { DrawerFooterSlots }; */

/* export { DrawerFooterState }; */

/* export { DrawerHeader }; */

/* export { drawerHeaderClassNames }; */

/* export { DrawerHeaderNavigation }; */

/* export { drawerHeaderNavigationClassNames }; */

/* export { DrawerHeaderNavigationProps }; */

/* export { DrawerHeaderNavigationSlots }; */

/* export { DrawerHeaderNavigationState }; */

/* export { DrawerHeaderProps }; */

/* export { DrawerHeaderSlots }; */

/* export { DrawerHeaderState }; */

/* export { DrawerHeaderTitle }; */

/* export { drawerHeaderTitleClassNames }; */

/* export { DrawerHeaderTitleProps }; */

/* export { DrawerHeaderTitleSlots }; */

/* export { DrawerHeaderTitleState }; */

/* export { DrawerProps }; */

/* export { DrawerSlots }; */

/* export { DrawerState }; */

/* export { Dropdown }; */

/* export { dropdownClassNames }; */

/* export { DropdownContextValues }; */

/* export { DropdownOpenChangeData }; */

/* export { DropdownOpenEvents }; */

/* export { DropdownProps }; */

/* export { DropdownSlots }; */

/* export { DropdownState }; */

/* export { DurationTokens }; */

/* export { Field }; */

/* export { fieldClassNames }; */

/* export { FieldContextProvider }; */

/* export { FieldContextValue }; */

/* export { FieldContextValues }; */

/* export { FieldControlProps }; */

/* export { FieldControlPropsOptions }; */

/* export { FieldProps }; */

/* export { FieldSlots }; */

/* export { FieldState }; */

/* export { flattenTree_unstable }; */

/* export { FlattenTreeItem }; */

/* export { FlatTree }; */

/* export { flatTreeClassNames }; */

/* export { FlatTreeItem }; */

/* export { FlatTreeItemProps }; */

/* export { FlatTreeProps }; */

/* export { FlatTreeSlots }; */

/* export { FlatTreeState }; */

/* export { FluentProvider }; */

/* export { fluentProviderClassNames }; */

/* export { FluentProviderContextValues }; */

/* export { FluentProviderCustomStyleHooks }; */

/* export { FluentProviderProps }; */

/* export { FluentProviderSlots }; */

/* export { FluentProviderState }; */

/* export { FontFamilyTokens }; */

/* export { FontSizeTokens }; */

/* export { FontWeightTokens }; */

/* export { ForwardRefComponent }; */

/* export { getIntrinsicElementProps }; */

/* export { getNativeElementProps }; */

/* export { getPartitionedNativeProps }; */

/* export { getSlots }; */

/* export { GriffelRenderer }; */

/* export { GriffelResetStyle }; */

/* export { GriffelStyle }; */

/* export { HeadlessFlatTree }; */

/* export { HeadlessFlatTreeItem }; */

/* export { HeadlessFlatTreeItemProps }; */

/* export { HeadlessFlatTreeOptions }; */

/* export { HorizontalSpacingTokens }; */

/* export { IdPrefixProvider }; */

/* export { Image_2 as Image }; */

/* export { imageClassNames }; */

/* export { ImageProps }; */

/* export { ImageSlots }; */

/* export { ImageState }; */

/* export { InfoLabel }; */

/* export { infoLabelClassNames }; */

/* export { InfoLabelProps }; */

/* export { InfoLabelSlots }; */

/* export { InfoLabelState }; */

/* export { InlineDrawer }; */

/* export { inlineDrawerClassNames }; */

/* export { InlineDrawerProps }; */

/* export { InlineDrawerSlots }; */

/* export { InlineDrawerState }; */

/* export { Input }; */

/* export { inputClassNames }; */

/* export { InputOnChangeData }; */

/* export { InputProps }; */

/* export { InputSlots }; */

/* export { InputState }; */

/* export { InteractionTag }; */

/* export { interactionTagClassNames }; */

/* export { InteractionTagPrimary }; */

/* export { interactionTagPrimaryClassNames }; */

/* export { InteractionTagPrimaryContextValues }; */

/* export { InteractionTagPrimaryProps }; */

/* export { InteractionTagPrimarySlots }; */

/* export { InteractionTagPrimaryState }; */

/* export { InteractionTagProps }; */

/* export { InteractionTagSecondary }; */

/* export { interactionTagSecondaryClassNames }; */

/* export { InteractionTagSecondaryProps }; */

/* export { InteractionTagSecondarySlots }; */

/* export { InteractionTagSecondaryState }; */

/* export { InteractionTagSlots }; */

/* export { InteractionTagState }; */

/* export { isTruncatableBreadcrumbContent }; */

/* export { Label }; */

/* export { labelClassNames }; */

/* export { LabelProps }; */

/* export { LabelSlots }; */

/* export { LabelState }; */

/* export { LargeTitle }; */

/* export { largeTitleClassNames }; */

/* export { LineHeightTokens }; */

/* export { Link }; */

/* export { linkClassNames }; */

/* export { LinkProps }; */

/* export { LinkSlots }; */

/* export { LinkState }; */

/* export { Listbox }; */

/* export { listboxClassNames }; */

/* export { ListboxContextValue }; */

/* export { ListboxContextValues }; */

/* export { ListboxProps }; */

/* export { ListboxProvider }; */

/* export { ListboxSlots }; */

/* export { ListboxState }; */

/* export { makeResetStyles }; */

/* export { makeStaticStyles }; */

/* export { makeStyles }; */

/* export { Menu }; */

/* export { MenuButton }; */

/* export { menuButtonClassNames }; */

/* export { MenuButtonProps }; */

/* export { MenuButtonSlots }; */

/* export { MenuButtonState }; */

/* export { MenuCheckedValueChangeData }; */

/* export { MenuCheckedValueChangeEvent }; */

/* export { MenuContextValue }; */

/* export { MenuContextValues }; */

/* export { MenuDivider }; */

/* export { menuDividerClassNames }; */

/* export { MenuDividerProps }; */

/* export { MenuDividerSlots }; */

/* export { MenuDividerState }; */

/* export { MenuGroup }; */

/* export { menuGroupClassNames }; */

/* export { MenuGroupContextProvider }; */

/* export { MenuGroupContextValue }; */

/* export { MenuGroupContextValues }; */

/* export { MenuGroupHeader }; */

/* export { menuGroupHeaderClassNames }; */

/* export { MenuGroupHeaderProps }; */

/* export { MenuGroupHeaderSlots }; */

/* export { MenuGroupHeaderState }; */

/* export { MenuGroupProps }; */

/* export { MenuGroupSlots }; */

/* export { MenuGroupState }; */

/* export { MenuItem }; */

/* export { MenuItemCheckbox }; */

/* export { menuItemCheckboxClassNames }; */

/* export { MenuItemCheckboxProps }; */

/* export { MenuItemCheckboxState }; */

/* export { menuItemClassNames }; */

/* export { MenuItemLink }; */

/* export { menuItemLinkClassNames }; */

/* export { MenuItemLinkProps }; */

/* export { MenuItemLinkSlots }; */

/* export { MenuItemLinkState }; */

/* export { MenuItemProps }; */

/* export { MenuItemRadio }; */

/* export { menuItemRadioClassNames }; */

/* export { MenuItemRadioProps }; */

/* export { MenuItemRadioState }; */

/* export { MenuItemSelectableProps }; */

/* export { MenuItemSelectableState }; */

/* export { MenuItemSlots }; */

/* export { MenuItemState }; */

/* export { MenuList }; */

/* export { menuListClassNames }; */

/* export { MenuListContextValue }; */

/* export { MenuListContextValues }; */

/* export { MenuListProps }; */

/* export { MenuListProvider }; */

/* export { MenuListSlots }; */

/* export { MenuListState }; */

/* export { MenuOpenChangeData }; */

/* export { MenuOpenEvent }; */

/* export { MenuOpenEvents }; */

/* export { MenuPopover }; */

/* export { menuPopoverClassNames }; */

/* export { MenuPopoverProps }; */

/* export { MenuPopoverSlots }; */

/* export { MenuPopoverState }; */

/* export { MenuProps }; */

/* export { MenuProvider }; */

/* export { MenuSlots }; */

/* export { MenuSplitGroup }; */

/* export { menuSplitGroupClassNames }; */

/* export { MenuSplitGroupProps }; */

/* export { MenuSplitGroupSlots }; */

/* export { MenuSplitGroupState }; */

/* export { MenuState }; */

/* export { MenuTrigger }; */

/* export { MenuTriggerChildProps }; */

/* export { MenuTriggerContextProvider }; */

/* export { MenuTriggerProps }; */

/* export { MenuTriggerState }; */

/* export { mergeCallbacks }; */

/* export { mergeClasses }; */

/* export { MessageBar }; */

/* export { MessageBarActions }; */

/* export { messageBarActionsClassNames }; */

/* export { MessageBarActionsProps }; */

/* export { MessageBarActionsSlots }; */

/* export { MessageBarActionsState }; */

/* export { MessageBarBody }; */

/* export { messageBarBodyClassNames }; */

/* export { MessageBarBodyProps }; */

/* export { MessageBarBodySlots }; */

/* export { MessageBarBodyState }; */

/* export { messageBarClassNames }; */

/* export { MessageBarContextProvider }; */

/* export { MessageBarContextValue }; */

/* export { MessageBarGroup }; */

/* export { messageBarGroupClassNames }; */

/* export { MessageBarGroupProps }; */

/* export { MessageBarGroupSlots }; */

/* export { MessageBarGroupState }; */

/* export { MessageBarIntent }; */

/* export { MessageBarProps }; */

/* export { MessageBarSlots }; */

/* export { MessageBarState }; */

/* export { MessageBarTitle }; */

/* export { messageBarTitleClassNames }; */

/* export { MessageBarTitleProps }; */

/* export { MessageBarTitleSlots }; */

/* export { MessageBarTitleState }; */

/* export { OnOpenChangeData }; */

/* export { OnSelectionChangeCallback }; */

/* export { OnSelectionChangeData }; */

/* export { OnVisibleChangeData }; */

/* export { OpenPopoverEvents }; */

/* export { Option_2 as Option }; */

/* export { optionClassNames }; */

/* export { OptionGroup }; */

/* export { optionGroupClassNames }; */

/* export { OptionGroupProps }; */

/* export { OptionGroupSlots }; */

/* export { OptionGroupState }; */

/* export { OptionOnSelectData }; */

/* export { OptionProps }; */

/* export { OptionSlots }; */

/* export { OptionState }; */

/* export { Overflow }; */

/* export { OverflowDivider }; */

/* export { OverflowItem }; */

/* export { OverflowItemProps }; */

/* export { OverflowProps }; */

/* export { OverlayDrawer }; */

/* export { overlayDrawerClassNames }; */

/* export { OverlayDrawerProps }; */

/* export { OverlayDrawerSlots }; */

/* export { OverlayDrawerState }; */

/* export { PartialTheme }; */

/* export { PartitionAvatarGroupItems }; */

/* export { partitionAvatarGroupItems }; */

/* export { PartitionAvatarGroupItemsOptions }; */

/* export { PartitionBreadcrumbItems }; */

/* export { partitionBreadcrumbItems }; */

/* export { PartitionBreadcrumbItemsOptions }; */

/* export { Persona }; */

/* export { personaClassNames }; */

/* export { PersonaProps }; */

/* export { PersonaSlots }; */

/* export { PersonaState }; */

/* export { Popover }; */

/* export { PopoverContextValue }; */

/* export { PopoverProps }; */

/* export { PopoverProvider }; */

/* export { PopoverSize }; */

/* export { PopoverState }; */

/* export { PopoverSurface }; */

/* export { popoverSurfaceClassNames }; */

/* export { PopoverSurfaceProps }; */

/* export { PopoverSurfaceSlots }; */

/* export { PopoverSurfaceState }; */

/* export { PopoverTrigger }; */

/* export { PopoverTriggerChildProps }; */

/* export { PopoverTriggerProps }; */

/* export { PopoverTriggerState }; */

/* export { Portal }; */

/* export { PortalMountNodeProvider }; */

/* export { PortalProps }; */

/* export { PortalState }; */

/* export { PositioningImperativeRef }; */

/* export { PositioningProps }; */

/* export { PositioningShorthand }; */

/* export { PositioningShorthandValue }; */

/* export { PositioningVirtualElement }; */

/* export { presenceAvailableFilled }; */

/* export { presenceAvailableRegular }; */

/* export { presenceAwayFilled }; */

/* export { presenceAwayRegular }; */

/* export { PresenceBadge }; */

/* export { presenceBadgeClassNames }; */

/* export { PresenceBadgeProps }; */

/* export { PresenceBadgeState }; */

/* export { PresenceBadgeStatus }; */

/* export { presenceBlockedRegular }; */

/* export { presenceBusyFilled }; */

/* export { presenceDndFilled }; */

/* export { presenceDndRegular }; */

/* export { presenceOfflineRegular }; */

/* export { presenceOofRegular }; */

/* export { presenceUnknownRegular }; */

/* export { ProgressBar }; */

/* export { progressBarClassNames }; */

/* export { ProgressBarProps }; */

/* export { ProgressBarSlots }; */

/* export { ProgressBarState }; */

/* export { Radio }; */

/* export { radioClassNames }; */

/* export { RadioGroup }; */

/* export { radioGroupClassNames }; */

/* export { RadioGroupContextValue }; */

/* export { RadioGroupContextValues }; */

/* export { RadioGroupOnChangeData }; */

/* export { RadioGroupProps }; */

/* export { RadioGroupProvider }; */

/* export { RadioGroupSlots }; */

/* export { RadioGroupState }; */

/* export { RadioOnChangeData }; */

/* export { RadioProps }; */

/* export { RadioSlots }; */

/* export { RadioState }; */

/* export { RegisterTabEventHandler }; */

/* export { renderAccordion_unstable }; */

/* export { renderAccordionHeader_unstable }; */

/* export { renderAccordionItem_unstable }; */

/* export { renderAccordionPanel_unstable }; */

/* export { renderAriaLiveAnnouncer_unstable }; */

/* export { renderAvatar_unstable }; */

/* export { renderAvatarGroup_unstable }; */

/* export { renderAvatarGroupItem_unstable }; */

/* export { renderAvatarGroupPopover_unstable }; */

/* export { renderBadge_unstable }; */

/* export { renderBreadcrumb_unstable }; */

/* export { renderBreadcrumbButton_unstable }; */

/* export { renderBreadcrumbDivider_unstable }; */

/* export { renderBreadcrumbItem_unstable }; */

/* export { renderButton_unstable }; */

/* export { renderCard_unstable }; */

/* export { renderCardFooter_unstable }; */

/* export { renderCardHeader_unstable }; */

/* export { renderCardPreview_unstable }; */

/* export { renderCheckbox_unstable }; */

/* export { renderCombobox_unstable }; */

/* export { renderCompoundButton_unstable }; */

/* export { renderDataGrid_unstable }; */

/* export { renderDataGridBody_unstable }; */

/* export { renderDataGridCell_unstable }; */

/* export { renderDataGridHeader_unstable }; */

/* export { renderDataGridHeaderCell_unstable }; */

/* export { renderDataGridRow_unstable }; */

/* export { renderDataGridSelectionCell_unstable }; */

/* export { renderDialog_unstable }; */

/* export { renderDialogActions_unstable }; */

/* export { renderDialogBody_unstable }; */

/* export { renderDialogContent_unstable }; */

/* export { renderDialogSurface_unstable }; */

/* export { renderDialogTitle_unstable }; */

/* export { renderDialogTrigger_unstable }; */

/* export { renderDivider_unstable }; */

/* export { renderDrawer_unstable }; */

/* export { renderDrawerBody_unstable }; */

/* export { renderDrawerFooter_unstable }; */

/* export { renderDrawerHeader_unstable }; */

/* export { renderDrawerHeaderNavigation_unstable }; */

/* export { renderDrawerHeaderTitle_unstable }; */

/* export { renderDropdown_unstable }; */

/* export { RendererProvider }; */

/* export { renderField_unstable }; */

/* export { renderFlatTree_unstable }; */

/* export { renderFluentProvider_unstable }; */

/* export { renderImage_unstable }; */

/* export { renderInfoLabel_unstable }; */

/* export { renderInlineDrawer_unstable }; */

/* export { renderInput_unstable }; */

/* export { renderInteractionTag_unstable }; */

/* export { renderInteractionTagPrimary_unstable }; */

/* export { renderInteractionTagSecondary_unstable }; */

/* export { renderLabel_unstable }; */

/* export { renderLink_unstable }; */

/* export { renderListbox_unstable }; */

/* export { renderMenu_unstable }; */

/* export { renderMenuButton_unstable }; */

/* export { renderMenuDivider_unstable }; */

/* export { renderMenuGroup_unstable }; */

/* export { renderMenuGroupHeader_unstable }; */

/* export { renderMenuItem_unstable }; */

/* export { renderMenuItemCheckbox_unstable }; */

/* export { renderMenuItemLink_unstable }; */

/* export { renderMenuItemRadio_unstable }; */

/* export { renderMenuList_unstable }; */

/* export { renderMenuPopover_unstable }; */

/* export { renderMenuSplitGroup_unstable }; */

/* export { renderMenuTrigger_unstable }; */

/* export { renderMessageBar_unstable }; */

/* export { renderMessageBarActions_unstable }; */

/* export { renderMessageBarBody_unstable }; */

/* export { renderMessageBarGroup_unstable }; */

/* export { renderMessageBarTitle_unstable }; */

/* export { renderOption_unstable }; */

/* export { renderOptionGroup_unstable }; */

/* export { renderOverlayDrawer_unstable }; */

/* export { renderPersona_unstable }; */

/* export { renderPopover_unstable }; */

/* export { renderPopoverSurface_unstable }; */

/* export { renderPopoverTrigger_unstable }; */

/* export { renderPortal_unstable }; */

/* export { renderProgressBar_unstable }; */

/* export { renderRadio_unstable }; */

/* export { renderRadioGroup_unstable }; */

/* export { renderSelect_unstable }; */

/* export { renderSkeleton_unstable }; */

/* export { renderSkeletonItem_unstable }; */

/* export { renderSlider_unstable }; */

/* export { renderSpinButton_unstable }; */

/* export { renderSpinner_unstable }; */

/* export { renderSplitButton_unstable }; */

/* export { renderSwitch_unstable }; */

/* export { renderTab_unstable }; */

/* export { renderTable_unstable }; */

/* export { renderTableBody_unstable }; */

/* export { renderTableCell_unstable }; */

/* export { renderTableCellActions_unstable }; */

/* export { renderTableCellLayout_unstable }; */

/* export { renderTableHeader_unstable }; */

/* export { renderTableHeaderCell_unstable }; */

/* export { renderTableResizeHandle_unstable }; */

/* export { renderTableRow_unstable }; */

/* export { renderTableSelectionCell_unstable }; */

/* export { renderTabList_unstable }; */

/* export { renderTag_unstable }; */

/* export { renderTagGroup_unstable }; */

/* export { renderText_unstable }; */

/* export { renderTextarea_unstable }; */

/* export { renderToast_unstable }; */

/* export { renderToastBody_unstable }; */

/* export { renderToaster_unstable }; */

/* export { renderToastFooter_unstable }; */

/* export { renderToastTitle_unstable }; */

/* export { renderToastTrigger_unstable }; */

/* export { renderToggleButton_unstable }; */

/* export { renderToolbar_unstable }; */

/* export { renderToolbarGroup_unstable }; */

/* export { renderTooltip_unstable }; */

/* export { renderToStyleElements }; */

/* export { renderTree_unstable }; */

/* export { renderTreeItem_unstable }; */

/* export { renderTreeItemLayout_unstable }; */

/* export { renderTreeItemPersonaLayout_unstable }; */

/* export { resetIdsForTests }; */

/* export { resolvePositioningShorthand }; */

/* export { resolveShorthand }; */

/* export { ResolveShorthandFunction }; */

/* export { ResolveShorthandOptions }; */

/* export { Select }; */

/* export { SelectableHandler }; */

/* export { selectClassNames }; */

/* export { SelectionEvents }; */

/* export { SelectionHookParams }; */

/* export { SelectionItemId }; */

/* export { SelectionMethods }; */

/* export { SelectionMode_2 as SelectionMode }; */

/* export { SelectOnChangeData }; */

/* export { SelectProps }; */

/* export { SelectSlots }; */

/* export { SelectState }; */

/* export { SelectTabData }; */

/* export { SelectTabEvent }; */

/* export { SelectTabEventHandler }; */

/* export { ShadowBrandTokens }; */

/* export { ShadowTokens }; */

/* export { shorthands }; */

/* export { Skeleton }; */

/* export { skeletonClassNames }; */

/* export { SkeletonContextProvider }; */

/* export { SkeletonContextValue }; */

/* export { SkeletonItem }; */

/* export { skeletonItemClassNames }; */

/* export { SkeletonItemProps }; */

/* export { SkeletonItemSlots }; */

/* export { SkeletonItemState }; */

/* export { SkeletonProps }; */

/* export { SkeletonSlots }; */

/* export { SkeletonState }; */

/* export { Slider }; */

/* export { sliderClassNames }; */

/* export { sliderCSSVars }; */

/* export { SliderOnChangeData }; */

/* export { SliderProps }; */

/* export { SliderSlots }; */

/* export { SliderState }; */

/* export { Slot }; */

/* export { slot }; */

/* export { SlotClassNames }; */

/* export { SlotComponentType }; */

/* export { SlotOptions }; */

/* export { SlotPropsRecord }; */

/* export { SlotRenderFunction }; */

/* export { SortDirection }; */

/* export { SpacingTokens }; */

/* export { SpinButton }; */

/* export { SpinButtonBounds }; */

/* export { SpinButtonChangeEvent }; */

/* export { spinButtonClassNames }; */

/* export { SpinButtonOnChangeData }; */

/* export { SpinButtonProps }; */

/* export { SpinButtonSlots }; */

/* export { SpinButtonSpinState }; */

/* export { SpinButtonState }; */

/* export { Spinner }; */

/* export { spinnerClassNames }; */

/* export { SpinnerProps }; */

/* export { SpinnerSlots }; */

/* export { SpinnerState }; */

/* export { SplitButton }; */

/* export { splitButtonClassNames }; */

/* export { SplitButtonProps }; */

/* export { SplitButtonSlots }; */

/* export { SplitButtonState }; */

/* export { SSRProvider }; */

/* export { StrokeWidthTokens }; */

/* export { Subtitle1 }; */

/* export { subtitle1ClassNames }; */

/* export { Subtitle2 }; */

/* export { subtitle2ClassNames }; */

/* export { Subtitle2Stronger }; */

/* export { subtitle2StrongerClassNames }; */

/* export { SubtreeContextValue }; */

/* export { Switch }; */

/* export { switchClassNames }; */

/* export { SwitchOnChangeData }; */

/* export { SwitchProps }; */

/* export { SwitchSlots }; */

/* export { SwitchState }; */

/* export { Tab }; */

/* export { tabClassNames }; */

/* export { Table }; */

/* export { TableBody }; */

/* export { tableBodyClassName }; */

/* export { tableBodyClassNames }; */

/* export { TableBodyProps }; */

/* export { TableBodySlots }; */

/* export { TableBodyState }; */

/* export { TableCell }; */

/* export { TableCellActions }; */

/* export { tableCellActionsClassNames }; */

/* export { TableCellActionsProps }; */

/* export { TableCellActionsSlots }; */

/* export { TableCellActionsState }; */

/* export { tableCellClassName }; */

/* export { tableCellClassNames }; */

/* export { TableCellLayout }; */

/* export { tableCellLayoutClassNames }; */

/* export { TableCellLayoutProps }; */

/* export { TableCellLayoutSlots }; */

/* export { TableCellLayoutState }; */

/* export { TableCellProps }; */

/* export { TableCellSlots }; */

/* export { TableCellState }; */

/* export { tableClassName }; */

/* export { tableClassNames }; */

/* export { TableColumnDefinition }; */

/* export { TableColumnId }; */

/* export { TableColumnSizingOptions }; */

/* export { TableContextProvider }; */

/* export { TableContextValue }; */

/* export { TableContextValues }; */

/* export { TableFeaturePlugin }; */

/* export { TableFeaturesState }; */

/* export { TableHeader }; */

/* export { TableHeaderCell }; */

/* export { tableHeaderCellClassName }; */

/* export { tableHeaderCellClassNames }; */

/* export { TableHeaderCellProps }; */

/* export { TableHeaderCellSlots }; */

/* export { TableHeaderCellState }; */

/* export { tableHeaderClassName }; */

/* export { tableHeaderClassNames }; */

/* export { TableHeaderContextProvider }; */

/* export { TableHeaderProps }; */

/* export { TableHeaderSlots }; */

/* export { TableHeaderState }; */

/* export { TableProps }; */

/* export { TableResizeHandle }; */

/* export { tableResizeHandleClassNames }; */

/* export { TableRow }; */

/* export { tableRowClassName }; */

/* export { tableRowClassNames }; */

/* export { TableRowData }; */

/* export { TableRowId }; */

/* export { TableRowIdContextProvider }; */

/* export { TableRowProps }; */

/* export { TableRowSlots }; */

/* export { TableRowState }; */

/* export { TableSelectionCell }; */

/* export { tableSelectionCellClassNames }; */

/* export { TableSelectionCellProps }; */

/* export { TableSelectionCellSlots }; */

/* export { TableSelectionCellState }; */

/* export { TableSelectionState }; */

/* export { TableSlots }; */

/* export { TableSortState }; */

/* export { TableState }; */

/* export { TabList }; */

/* export { tabListClassNames }; */

/* export { TabListContextValue }; */

/* export { TabListContextValues }; */

/* export { TabListProps }; */

/* export { TabListProvider }; */

/* export { TabListSlots }; */

/* export { TabListState }; */

/* export { TabProps }; */

/* export { TabRegisterData }; */

/* export { TabSlots }; */

/* export { TabState }; */

/* export { TabValue }; */

/* export { Tag }; */

/* export { TagAppearance }; */

/* export { tagClassNames }; */

/* export { TagDismissData }; */

/* export { TagDismissEvent }; */

/* export { TagDismissHandler }; */

/* export { TagGroup }; */

/* export { tagGroupClassNames }; */

/* export { TagGroupProps }; */

/* export { TagGroupSlots }; */

/* export { TagGroupState }; */

/* export { TagProps }; */

/* export { TagShape }; */

/* export { TagSize }; */

/* export { TagSlots }; */

/* export { TagState }; */

/* export { TagValue }; */

/* export { teamsDarkTheme }; */

/* export { teamsHighContrastTheme }; */

/* export { teamsLightTheme }; */

/* export { Text_2 as Text }; */

/* export { Textarea }; */

/* export { textareaClassNames }; */

/* export { TextareaOnChangeData }; */

/* export { TextareaProps }; */

/* export { TextareaSlots }; */

/* export { TextareaState }; */

/* export { textClassNames }; */

/* export { TextPresetProps }; */

/* export { TextProps }; */

/* export { TextSlots }; */

/* export { TextState }; */

/* export { Theme }; */

/* export { themeToTokensObject }; */

/* export { Title1 }; */

/* export { title1ClassNames }; */

/* export { Title2 }; */

/* export { title2ClassNames }; */

/* export { Title3 }; */

/* export { title3ClassNames }; */

/* export { Toast }; */

/* export { ToastBody }; */

/* export { toastBodyClassNames }; */

/* export { ToastBodyProps }; */

/* export { ToastBodySlots }; */

/* export { ToastBodyState }; */

/* export { Toaster }; */

/* export { toasterClassNames }; */

/* export { ToasterProps }; */

/* export { ToasterSlots }; */

/* export { ToasterState }; */

/* export { ToastFooter }; */

/* export { toastFooterClassNames }; */

/* export { ToastFooterProps }; */

/* export { ToastFooterSlots }; */

/* export { ToastFooterState }; */

/* export { ToastId }; */

/* export { ToastIntent }; */

/* export { ToastOffset }; */

/* export { ToastPoliteness }; */

/* export { ToastPosition }; */

/* export { ToastProps }; */

/* export { ToastSlots }; */

/* export { ToastState }; */

/* export { ToastStatus }; */

/* export { ToastTitle }; */

/* export { toastTitleClassNames }; */

/* export { ToastTitleProps }; */

/* export { ToastTitleSlots }; */

/* export { ToastTitleState }; */

/* export { ToastTrigger }; */

/* export { ToastTriggerChildProps }; */

/* export { ToastTriggerProps }; */

/* export { ToastTriggerState }; */

/* export { ToggleButton }; */

/* export { toggleButtonClassNames }; */

/* export { ToggleButtonProps }; */

/* export { ToggleButtonState }; */

/* export { tokens }; */

/* export { toMountNodeProps }; */

/* export { Toolbar }; */

/* export { ToolbarButton }; */

/* export { ToolbarButtonProps }; */

/* export { ToolbarButtonState }; */

/* export { toolbarClassNames }; */

/* export { ToolbarContextValue }; */

/* export { ToolbarContextValues }; */

/* export { ToolbarDivider }; */

/* export { ToolbarDividerProps }; */

/* export { ToolbarDividerState }; */

/* export { ToolbarGroup }; */

/* export { toolbarGroupClassNames }; */

/* export { ToolbarGroupProps }; */

/* export { ToolbarGroupState }; */

/* export { ToolbarProps }; */

/* export { ToolbarRadioButton }; */

/* export { ToolbarRadioButtonProps }; */

/* export { ToolbarRadioButtonState }; */

/* export { ToolbarRadioGroup }; */

/* export { ToolbarRadioGroupProps }; */

/* export { ToolbarRadioGroupState }; */

/* export { ToolbarSlots }; */

/* export { ToolbarState }; */

/* export { ToolbarToggleButton }; */

/* export { ToolbarToggleButtonProps }; */

/* export { ToolbarToggleButtonState }; */

/* export { Tooltip }; */

/* export { tooltipClassNames }; */

/* export { TooltipProps }; */

/* export { TooltipSlots }; */

/* export { TooltipState }; */

/* export { TooltipTriggerProps }; */

/* export { Tree }; */

/* export { TreeCheckedChangeData }; */

/* export { TreeCheckedChangeEvent }; */

/* export { treeClassNames }; */

/* export { TreeContextValue }; */

/* export { TreeContextValues }; */

/* export { TreeItem }; */

/* export { treeItemClassNames }; */

/* export { TreeItemContextValue }; */

/* export { TreeItemLayout }; */

/* export { treeItemLayoutClassNames }; */

/* export { TreeItemLayoutProps }; */

/* export { TreeItemLayoutSlots }; */

/* export { TreeItemLayoutState }; */

/* export { treeItemLevelToken }; */

/* export { TreeItemOpenChangeData }; */

/* export { TreeItemOpenChangeEvent }; */

/* export { TreeItemPersonaLayout }; */

/* export { treeItemPersonaLayoutClassNames }; */

/* export { TreeItemPersonaLayoutProps }; */

/* export { TreeItemPersonaLayoutSlots }; */

/* export { TreeItemPersonaLayoutState }; */

/* export { TreeItemProps }; */

/* export { TreeItemProvider }; */

/* export { TreeItemSlots }; */

/* export { TreeItemState }; */

/* export { TreeItemValue }; */

/* export { TreeNavigationData_unstable }; */

/* export { TreeNavigationEvent_unstable }; */

/* export { TreeOpenChangeData }; */

/* export { TreeOpenChangeEvent }; */

/* export { TreeProps }; */

/* export { TreeProvider }; */

/* export { TreeSelectionValue }; */

/* export { TreeSlots }; */

/* export { TreeState }; */

/* export { truncateBreadcrumbLongName }; */

/* export { truncateBreadcrumLongTooltip }; */

/* export { TypographyStyle }; */

/* export { TypographyStyles }; */

/* export { typographyStyles }; */

/* export { UninitializedMenuListState }; */

/* export { useAccordion_unstable }; */

/* export { useAccordionContext_unstable }; */

/* export { useAccordionContextValues_unstable }; */

/* export { useAccordionHeader_unstable }; */

/* export { useAccordionHeaderContextValues_unstable }; */

/* export { useAccordionHeaderStyles_unstable }; */

/* export { useAccordionItem_unstable }; */

/* export { useAccordionItemContext_unstable }; */

/* export { useAccordionItemContextValues_unstable }; */

/* export { useAccordionItemStyles_unstable }; */

/* export { useAccordionPanel_unstable }; */

/* export { useAccordionPanelStyles_unstable }; */

/* export { useAccordionStyles_unstable }; */

/* export { useAnnounce }; */

/* export { useAriaLiveAnnouncer_unstable }; */

/* export { useAriaLiveAnnouncerContextValues_unstable }; */

/* export { useArrowNavigationGroup }; */

/* export { UseArrowNavigationGroupOptions }; */

/* export { useAvatar_unstable }; */

/* export { useAvatarGroup_unstable }; */

/* export { useAvatarGroupContext_unstable }; */

/* export { useAvatarGroupContextValues }; */

/* export { useAvatarGroupItem_unstable }; */

/* export { useAvatarGroupItemStyles_unstable }; */

/* export { useAvatarGroupPopover_unstable }; */

/* export { useAvatarGroupPopoverContextValues_unstable }; */

/* export { useAvatarGroupPopoverStyles_unstable }; */

/* export { useAvatarGroupStyles_unstable }; */

/* export { useAvatarStyles_unstable }; */

/* export { useBadge_unstable }; */

/* export { useBadgeStyles_unstable }; */

/* export { useBreadcrumb_unstable }; */

/* export { useBreadcrumbButton_unstable }; */

/* export { useBreadcrumbButtonStyles_unstable }; */

/* export { useBreadcrumbContext_unstable }; */

/* export { useBreadcrumbDivider_unstable }; */

/* export { useBreadcrumbDividerStyles_unstable }; */

/* export { useBreadcrumbItem_unstable }; */

/* export { useBreadcrumbItemStyles_unstable }; */

/* export { useBreadcrumbStyles_unstable }; */

/* export { useButton_unstable }; */

/* export { useButtonStyles_unstable }; */

/* export { useCard_unstable }; */

/* export { useCardFooter_unstable }; */

/* export { useCardFooterStyles_unstable }; */

/* export { useCardHeader_unstable }; */

/* export { useCardHeaderStyles_unstable }; */

/* export { useCardPreview_unstable }; */

/* export { useCardPreviewStyles_unstable }; */

/* export { useCardStyles_unstable }; */

/* export { useCheckbox_unstable }; */

/* export { useCheckboxStyles_unstable }; */

/* export { useCheckmarkStyles_unstable }; */

/* export { useColumnIdContext }; */

/* export { useCombobox_unstable }; */

/* export { useComboboxContextValues }; */

/* export { useComboboxFilter }; */

/* export { useComboboxStyles_unstable }; */

/* export { useCompoundButton_unstable }; */

/* export { useCompoundButtonStyles_unstable }; */

/* export { useCounterBadge_unstable }; */

/* export { useCounterBadgeStyles_unstable }; */

/* export { useDataGrid_unstable }; */

/* export { useDataGridBody_unstable }; */

/* export { useDataGridBodyStyles_unstable }; */

/* export { useDataGridCell_unstable }; */

/* export { useDataGridCellStyles_unstable }; */

/* export { useDataGridContext_unstable }; */

/* export { useDataGridContextValues_unstable }; */

/* export { useDataGridHeader_unstable }; */

/* export { useDataGridHeaderCell_unstable }; */

/* export { useDataGridHeaderCellStyles_unstable }; */

/* export { useDataGridHeaderStyles_unstable }; */

/* export { useDataGridRow_unstable }; */

/* export { useDataGridRowStyles_unstable }; */

/* export { useDataGridSelectionCell_unstable }; */

/* export { useDataGridSelectionCellStyles_unstable }; */

/* export { useDataGridStyles_unstable }; */

/* export { useDialog_unstable }; */

/* export { useDialogActions_unstable }; */

/* export { useDialogActionsStyles_unstable }; */

/* export { useDialogBody_unstable }; */

/* export { useDialogBodyStyles_unstable }; */

/* export { useDialogContent_unstable }; */

/* export { useDialogContentStyles_unstable }; */

/* export { useDialogContext_unstable }; */

/* export { useDialogSurface_unstable }; */

/* export { useDialogSurfaceContext_unstable }; */

/* export { useDialogSurfaceContextValues_unstable }; */

/* export { useDialogSurfaceStyles_unstable }; */

/* export { useDialogTitle_unstable }; */

/* export { useDialogTitleStyles_unstable }; */

/* export { useDialogTrigger_unstable }; */

/* export { useDivider_unstable }; */

/* export { useDividerStyles_unstable }; */

/* export { useDrawer_unstable }; */

/* export { useDrawerBody_unstable }; */

/* export { useDrawerBodyStyles_unstable }; */

/* export { useDrawerFooter_unstable }; */

/* export { useDrawerFooterStyles_unstable }; */

/* export { useDrawerHeader_unstable }; */

/* export { useDrawerHeaderNavigation_unstable }; */

/* export { useDrawerHeaderNavigationStyles_unstable }; */

/* export { useDrawerHeaderStyles_unstable }; */

/* export { useDrawerHeaderTitle_unstable }; */

/* export { useDrawerHeaderTitleStyles_unstable }; */

/* export { useDrawerStyles_unstable }; */

/* export { useDropdown_unstable }; */

/* export { useDropdownStyles_unstable }; */

/* export { useEventCallback }; */

/* export { useField_unstable }; */

/* export { useFieldContext_unstable }; */

/* export { useFieldContextValues_unstable }; */

/* export { useFieldControlProps_unstable }; */

/* export { useFieldStyles_unstable }; */

/* export { useFlatTree_unstable }; */

/* export { useFlatTreeContextValues_unstable }; */

/* export { useFlatTreeStyles_unstable }; */

/* export { useFluent }; */

/* export { useFluentProvider_unstable }; */

/* export { useFluentProviderContextValues_unstable }; */

/* export { useFluentProviderStyles_unstable }; */

/* export { useFluentProviderThemeStyleTag }; */

/* export { useFocusableGroup }; */

/* export { UseFocusableGroupOptions }; */

/* export { useFocusFinders }; */

/* export { useFocusObserved }; */

/* export { useFocusVisible }; */

/* export { useFocusWithin }; */

/* export { useHeadlessFlatTree_unstable }; */

/* export { useId }; */

/* export { useImage_unstable }; */

/* export { useImageStyles_unstable }; */

/* export { useInfoLabel_unstable }; */

/* export { useInfoLabelStyles_unstable }; */

/* export { useInlineDrawer_unstable }; */

/* export { useInlineDrawerStyles_unstable }; */

/* export { useInput_unstable }; */

/* export { useInputStyles_unstable }; */

/* export { useInteractionTag_unstable }; */

/* export { useInteractionTagContextValues_unstable }; */

/* export { useInteractionTagPrimary_unstable }; */

/* export { useInteractionTagPrimaryStyles_unstable }; */

/* export { useInteractionTagSecondary_unstable }; */

/* export { useInteractionTagSecondaryStyles_unstable }; */

/* export { useInteractionTagStyles_unstable }; */

/* export { useIsInTableHeader }; */

/* export { useIsomorphicLayoutEffect }; */

/* export { useIsOverflowGroupVisible }; */

/* export { useIsOverflowItemVisible }; */

/* export { useIsSSR }; */

/* export { useKeyboardNavAttribute }; */

/* export { useLabel_unstable }; */

/* export { useLabelStyles_unstable }; */

/* export { useLink_unstable }; */

/* export { useLinkState_unstable }; */

/* export { useLinkStyles_unstable }; */

/* export { useListbox_unstable }; */

/* export { useListboxContextValues }; */

/* export { useListboxStyles_unstable }; */

/* export { useMenu_unstable }; */

/* export { useMenuButton_unstable }; */

/* export { useMenuButtonStyles_unstable }; */

/* export { useMenuContext_unstable }; */

/* export { useMenuContextValues_unstable }; */

/* export { useMenuDivider_unstable }; */

/* export { useMenuDividerStyles_unstable }; */

/* export { useMenuGroup_unstable }; */

/* export { useMenuGroupContext_unstable }; */

/* export { useMenuGroupContextValues_unstable }; */

/* export { useMenuGroupHeader_unstable }; */

/* export { useMenuGroupHeaderStyles_unstable }; */

/* export { useMenuGroupStyles_unstable }; */

/* export { useMenuItem_unstable }; */

/* export { useMenuItemCheckbox_unstable }; */

/* export { useMenuItemCheckboxStyles_unstable }; */

/* export { useMenuItemLink_unstable }; */

/* export { useMenuItemLinkStyles_unstable }; */

/* export { useMenuItemRadio_unstable }; */

/* export { useMenuItemRadioStyles_unstable }; */

/* export { useMenuItemStyles_unstable }; */

/* export { useMenuList_unstable }; */

/* export { useMenuListContext_unstable }; */

/* export { useMenuListContextValues_unstable }; */

/* export { useMenuListStyles_unstable }; */

/* export { useMenuPopover_unstable }; */

/* export { useMenuPopoverStyles_unstable }; */

/* export { useMenuSplitGroup_unstable }; */

/* export { useMenuSplitGroupStyles_unstable }; */

/* export { useMenuTrigger_unstable }; */

/* export { useMenuTriggerContext_unstable }; */

/* export { useMergedRefs }; */

/* export { useMessageBar_unstable }; */

/* export { useMessageBarActions_unstable }; */

/* export { useMessageBarActionsStyles_unstable }; */

/* export { useMessageBarBody_unstable }; */

/* export { useMessageBarBodyStyles_unstable }; */

/* export { useMessageBarContext }; */

/* export { useMessageBarGroup_unstable }; */

/* export { useMessageBarGroupStyles_unstable }; */

/* export { useMessageBarStyles_unstable }; */

/* export { useMessageBarTitle_unstable }; */

/* export { useMessageBarTitleStyles_unstable }; */

/* export { useModalAttributes }; */

/* export { UseModalAttributesOptions }; */

/* export { useObservedElement }; */

/* export { useOption_unstable }; */

/* export { useOptionGroup_unstable }; */

/* export { useOptionGroupStyles_unstable }; */

/* export { useOptionStyles_unstable }; */

/* export { useOverflowCount }; */

/* export { useOverflowMenu }; */

/* export { useOverflowVisibility }; */

/* export { useOverlayDrawer_unstable }; */

/* export { useOverlayDrawerStyles_unstable }; */

/* export { usePersona_unstable }; */

/* export { usePersonaStyles_unstable }; */

/* export { usePopover_unstable }; */

/* export { usePopoverContext_unstable }; */

/* export { usePopoverSurface_unstable }; */

/* export { usePopoverSurfaceStyles_unstable }; */

/* export { usePopoverTrigger_unstable }; */

/* export { usePortal_unstable }; */

/* export { usePortalMountNode }; */

/* export { usePresenceBadge_unstable }; */

/* export { usePresenceBadgeStyles_unstable }; */

/* export { useProgressBar_unstable }; */

/* export { useProgressBarStyles_unstable }; */

/* export { useRadio_unstable }; */

/* export { useRadioGroup_unstable }; */

/* export { useRadioGroupContext_unstable }; */

/* export { useRadioGroupContextValue_unstable }; */

/* export { useRadioGroupContextValues }; */

/* export { useRadioGroupStyles_unstable }; */

/* export { useRadioStyles_unstable }; */

/* export { useRestoreFocusSource }; */

/* export { useRestoreFocusTarget }; */

/* export { useScrollbarWidth }; */

/* export { useSelect_unstable }; */

/* export { useSelection }; */

/* export { useSelectStyles_unstable }; */

/* export { useSkeleton_unstable }; */

/* export { useSkeletonContext }; */

/* export { useSkeletonItem_unstable }; */

/* export { useSkeletonItemStyles_unstable }; */

/* export { useSkeletonStyles_unstable }; */

/* export { useSlider_unstable }; */

/* export { useSliderState_unstable }; */

/* export { useSliderStyles_unstable }; */

/* export { useSpinButton_unstable }; */

/* export { useSpinButtonStyles_unstable }; */

/* export { useSpinner_unstable }; */

/* export { useSpinnerStyles_unstable }; */

/* export { useSplitButton_unstable }; */

/* export { useSplitButtonStyles_unstable }; */

/* export { useSubtreeContext_unstable }; */

/* export { useSwitch_unstable }; */

/* export { useSwitchStyles_unstable }; */

/* export { useTab_unstable }; */

/* export { useTable_unstable }; */

/* export { useTableBody_unstable }; */

/* export { useTableBodyStyles_unstable }; */

/* export { useTableCell_unstable }; */

/* export { useTableCellActions_unstable }; */

/* export { useTableCellActionsStyles_unstable }; */

/* export { useTableCellLayout_unstable }; */

/* export { useTableCellLayoutStyles_unstable }; */

/* export { useTableCellStyles_unstable }; */

/* export { useTableColumnSizing_unstable }; */

/* export { useTableCompositeNavigation }; */

/* export { useTableContext }; */

/* export { useTableFeatures }; */

/* export { UseTableFeaturesOptions }; */

/* export { useTableHeader_unstable }; */

/* export { useTableHeaderCell_unstable }; */

/* export { useTableHeaderCellStyles_unstable }; */

/* export { useTableHeaderStyles_unstable }; */

/* export { useTableResizeHandle_unstable }; */

/* export { useTableResizeHandleStyles_unstable }; */

/* export { useTableRow_unstable }; */

/* export { useTableRowIdContext }; */

/* export { useTableRowStyles_unstable }; */

/* export { useTableSelection }; */

/* export { useTableSelectionCell_unstable }; */

/* export { useTableSelectionCellStyles_unstable }; */

/* export { useTableSort }; */

/* export { useTableStyles_unstable }; */

/* export { useTabList_unstable }; */

/* export { useTabListContext_unstable }; */

/* export { useTabListContextValues_unstable }; */

/* export { useTabListStyles_unstable }; */

/* export { useTabStyles_unstable }; */

/* export { useTag_unstable }; */

/* export { useTagAvatarContextValues_unstable }; */

/* export { useTagGroup_unstable }; */

/* export { useTagGroupContextValues_unstable }; */

/* export { useTagGroupStyles_unstable }; */

/* export { useTagStyles_unstable }; */

/* export { useText_unstable }; */

/* export { useTextarea_unstable }; */

/* export { useTextareaStyles_unstable }; */

/* export { useTextStyles_unstable }; */

/* export { useThemeClassName }; */

/* export { useToast_unstable }; */

/* export { useToastBody_unstable }; */

/* export { useToastBodyStyles_unstable }; */

/* export { useToastController }; */

/* export { useToaster_unstable }; */

/* export { useToasterStyles_unstable }; */

/* export { useToastFooter_unstable }; */

/* export { useToastFooterStyles_unstable }; */

/* export { useToastStyles_unstable }; */

/* export { useToastTitle_unstable }; */

/* export { useToastTitleStyles_unstable }; */

/* export { useToastTrigger_unstable }; */

/* export { useToggleButton_unstable }; */

/* export { useToggleButtonStyles_unstable }; */

/* export { useToggleState }; */

/* export { useToolbar_unstable }; */

/* export { useToolbarButton_unstable }; */

/* export { useToolbarButtonStyles_unstable }; */

/* export { useToolbarDivider_unstable }; */

/* export { useToolbarDividerStyles_unstable }; */

/* export { useToolbarGroup_unstable }; */

/* export { useToolbarGroupStyles_unstable }; */

/* export { useToolbarRadioButton_unstable }; */

/* export { useToolbarRadioButtonStyles_unstable }; */

/* export { useToolbarStyles_unstable }; */

/* export { useToolbarToggleButton_unstable }; */

/* export { useToolbarToggleButtonStyles_unstable }; */

/* export { useTooltip_unstable }; */

/* export { useTooltipStyles_unstable }; */

/* export { useTooltipVisibility }; */

/* export { useTree_unstable }; */

/* export { useTreeContext_unstable }; */

/* export { useTreeContextValues_unstable }; */

/* export { useTreeItem_unstable }; */

/* export { useTreeItemContext_unstable }; */

/* export { useTreeItemContextValues_unstable }; */

/* export { useTreeItemLayout_unstable }; */

/* export { useTreeItemLayoutStyles_unstable }; */

/* export { useTreeItemPersonaLayout_unstable }; */

/* export { useTreeItemPersonaLayoutStyles_unstable }; */

/* export { useTreeItemStyles_unstable }; */

/* export { useTreeStyles_unstable }; */

/* export { useUncontrolledFocus }; */

/* export { VerticalSpacingTokens }; */

/* export { webDarkTheme }; */

/* export { webLightTheme }; */

/* export {}; */
