// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: DialogProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceSlots from "@fluentui/react-dialog" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 

/**
 * InlineDrawer Props
 */

sealed external interface InlineDrawerProps : InlineDrawerSlots, DrawerBaseProps {
    /**
     * Whether the drawer has a separator line.
     *
     * @default false
     */
    var separator: Boolean?
}
