// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ARIAButtonSlotProps from "@fluentui/react-aria" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


sealed external interface MenuButtonSlots : ButtonSlots {
    /**
     * Menu icon that indicates that this button has a menu that can be expanded.
     */
    var menuIcon: Slot
}
