// Generated by Karakum - do not modify it manually!


package fluentui


sealed external interface SkeletonContextValue {
    var animation: (SkeletonContextValueAnimation)?
    var appearance: (SkeletonContextValueAppearance)?
}
