// Generated by Karakum - do not modify it manually!


package fluentui


/**
 * State used in rendering SkeletonItem
 */

sealed external interface SkeletonItemState : SkeletonItemSlots, SkeletonItemProps
