// Generated by Karakum - do not modify it manually!


package fluentui

import react.Props


/**
 * Skeleton Props
 */

sealed external interface SkeletonProps : SkeletonSlots, Props {
    /**
     * The animation type for the Skeleton
     * @defaultValue wave
     */
    var animation: (Temp112)?

    /**
     * Sets the appearance of the Skeleton.
     * @defaultValue opaque
     */
    var appearance: (Temp113)?

    /**
     * Sets the width value of the skeleton wrapper.
     * @defaultValue 100%
     */
    var width: (Any /* number | string */)?
}
