// Generated by Karakum - do not modify it manually!


package fluentui

import react.PropsWithChildren
import react.ReactElement

// unhandled import: DispatchWithoutAction from "react" 

/**
 * A definition of a slot, as a component, very similar to how a React component is declared,
 * but with some additional metadata that is used to determine how to render the slot.
 */

sealed external interface SlotComponentType<Props : react.Props> {
    /**
     * **NOTE**: Slot components are not callable.
     */

    @seskar.js.JsNative
    operator fun invoke(props: PropsWithChildren): ReactElement<Props>
}
