// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: DispatchWithoutAction from "react" 

/**
 * @deprecated - use slot.always or slot.optional combined with assertSlots instead
 */

external interface Slots<S : SlotPropsRecord> {

    @seskar.js.JsNative
    operator fun <K : /* keyof S */Any> get(key: K): (Any /* ExtractSlotProps<S[K]> extends AsIntrinsicElement<infer As> ? As : ExtractSlotProps<S[K]> extends React_2.ComponentType<infer P> ? React_2.ElementType<NonNullable<P>> : React_2.ElementType<ExtractSlotProps<S[K]>> */)?


    @seskar.js.JsNative
    operator fun <K : /* keyof S */Any> set(
        key: K,
        value: (Any /* ExtractSlotProps<S[K]> extends AsIntrinsicElement<infer As> ? As : ExtractSlotProps<S[K]> extends React_2.ComponentType<infer P> ? React_2.ElementType<NonNullable<P>> : React_2.ElementType<ExtractSlotProps<S[K]>> */)?,
    )

}
