// Generated by Karakum - do not modify it manually!


package fluentui

import js.objects.ReadonlyRecord

// unhandled import: DispatchWithoutAction from "react" 

/**
 * Matches any component's Slots type (such as ButtonSlots).
 *
 * This should ONLY be used in type templates as in `extends SlotPropsRecord`;
 * it shouldn't be used as a component's Slots type.
 */
typealias SlotPropsRecord = ReadonlyRecord<String, Any? /* UnknownSlotProps | SlotShorthandValue | null | undefined */>
