// Generated by Karakum - do not modify it manually!


package fluentui

import react.ElementType
import react.ReactNode

// unhandled import: DispatchWithoutAction from "react" 

typealias SlotRenderFunction<Props> = (Component: ElementType<Props>, props: Props) -> ReactNode
