// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: DispatchWithoutAction from "react" 

/**
 * The shorthand value of a slot allows specifying its child
 */
typealias SlotShorthandValue = Any? /* React_2.ReactChild | React_2.ReactNode[] | React_2.ReactPortal */
