// Generated by Karakum - do not modify it manually!


package fluentui

import react.Props

// unhandled import: DispatchWithoutAction from "react" 


external interface SlotComponents<Slots : SlotPropsRecord> {

    @seskar.js.JsNative
    operator fun <K : /* keyof Slots */Any> get(key: K): SlotComponentType<Props>?


    @seskar.js.JsNative
    operator fun <K : /* keyof Slots */Any> set(key: K, value: SlotComponentType<Props>?)

}
