// Generated by Karakum - do not modify it manually!


package fluentui

// unhandled import: ARIAButtonSlotProps from "@fluentui/react-aria" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


sealed external interface SplitButtonSlots {
    /**
     * Root of the component that wraps the primary action button and menu button.
     */
    var root: Slot

    /**
     * Button that opens menu with secondary actions in SplitButton.
     */
    var menuButton: Slot

    /**
     * Button to perform primary action in SplitButton.
     */
    var primaryActionButton: Slot
}
