// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: FunctionComponent from "react" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp76 {
    companion object {
        @seskar.js.JsValue("h1")
        val h1: Temp76

        @seskar.js.JsValue("h2")
        val h2: Temp76

        @seskar.js.JsValue("h3")
        val h3: Temp76

        @seskar.js.JsValue("h4")
        val h4: Temp76

        @seskar.js.JsValue("h5")
        val h5: Temp76

        @seskar.js.JsValue("h6")
        val h6: Temp76

        @seskar.js.JsValue("p")
        val p: Temp76

        @seskar.js.JsValue("pre")
        val pre: Temp76

        @seskar.js.JsValue("strong")
        val strong: Temp76

        @seskar.js.JsValue("b")
        val b: Temp76

        @seskar.js.JsValue("em")
        val em: Temp76

        @seskar.js.JsValue("i")
        val i: Temp76
    }
}
