// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: FunctionComponent from "react" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp75 {
    companion object {
        @seskar.js.JsValue("regular")
        val regular: Temp75

        @seskar.js.JsValue("medium")
        val medium: Temp75

        @seskar.js.JsValue("semibold")
        val semibold: Temp75

        @seskar.js.JsValue("bold")
        val bold: Temp75
    }
}
