// Generated by Karakum - do not modify it manually!

package fluentui


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp29 {
    companion object {
        @seskar.js.JsValue("brand")
        val brand: Temp29

        @seskar.js.JsValue("danger")
        val danger: Temp29

        @seskar.js.JsValue("important")
        val important: Temp29

        @seskar.js.JsValue("informative")
        val informative: Temp29

        @seskar.js.JsValue("severe")
        val severe: Temp29

        @seskar.js.JsValue("subtle")
        val subtle: Temp29

        @seskar.js.JsValue("success")
        val success: Temp29

        @seskar.js.JsValue("warning")
        val warning: Temp29
    }
}
