// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ButtonProps from "@fluentui/react-button" 
// unhandled import: ButtonSlots from "@fluentui/react-button" 
// unhandled import: ButtonState from "@fluentui/react-button" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: DividerSlots from "@fluentui/react-divider" 
// unhandled import: DividerState from "@fluentui/react-divider" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 
// unhandled import: ToggleButtonProps from "@fluentui/react-button" 
// unhandled import: ToggleButtonState from "@fluentui/react-button" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp70 {
    companion object {
        @seskar.js.JsValue("small")
        val small: Temp70

        @seskar.js.JsValue("medium")
        val medium: Temp70

        @seskar.js.JsValue("large")
        val large: Temp70
    }
}
