// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: DialogProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceProps from "@fluentui/react-dialog" 
// unhandled import: DialogSurfaceSlots from "@fluentui/react-dialog" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp151 {
    companion object {
        @seskar.js.JsValue("inline")
        val inline: Temp151

        @seskar.js.JsValue("overlay")
        val overlay: Temp151
    }
}
