// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Label from "@fluentui/react-label" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp102 {
    companion object {
        @seskar.js.JsValue("extra-tiny")
        val extraTiny: Temp102

        @seskar.js.JsValue("tiny")
        val tiny: Temp102

        @seskar.js.JsValue("extra-small")
        val extraSmall: Temp102

        @seskar.js.JsValue("small")
        val small: Temp102

        @seskar.js.JsValue("medium")
        val medium: Temp102

        @seskar.js.JsValue("large")
        val large: Temp102

        @seskar.js.JsValue("extra-large")
        val extraLarge: Temp102

        @seskar.js.JsValue("huge")
        val huge: Temp102
    }
}
