// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp148 {
    companion object {
        @seskar.js.JsValue("none")
        val none: Temp148

        @seskar.js.JsValue("center")
        val center: Temp148

        @seskar.js.JsValue("contain")
        val contain: Temp148

        @seskar.js.JsValue("cover")
        val cover: Temp148

        @seskar.js.JsValue("default")
        val default: Temp148
    }
}
