// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: DispatchWithoutAction from "react" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp2 {
    companion object {
        @seskar.js.JsValue("ltr")
        val ltr: Temp2

        @seskar.js.JsValue("rtl")
        val rtl: Temp2
    }
}
