// Generated by Karakum - do not modify it manually!

package fluentui


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp34 {
    companion object {
        @seskar.js.JsValue("medium")
        val medium: Temp34

        @seskar.js.JsValue("small")
        val small: Temp34

        @seskar.js.JsValue("large")
        val large: Temp34

        @seskar.js.JsValue("tiny")
        val tiny: Temp34

        @seskar.js.JsValue("extra-small")
        val extraSmall: Temp34

        @seskar.js.JsValue("extra-large")
        val extraLarge: Temp34
    }
}
