// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ArrowDown from "@fluentui/keyboard-keys" 
// unhandled import: ArrowLeft from "@fluentui/keyboard-keys" 
// unhandled import: ArrowRight from "@fluentui/keyboard-keys" 
// unhandled import: ArrowUp from "@fluentui/keyboard-keys" 
// unhandled import: AvatarContextValue from "@fluentui/react-avatar" 
// unhandled import: AvatarSize from "@fluentui/react-avatar" 
// unhandled import: ButtonContextValue from "@fluentui/react-button" 
// unhandled import: Checkbox from "@fluentui/react-checkbox" 
// unhandled import: CheckboxProps from "@fluentui/react-checkbox" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ContextSelector from "@fluentui/react-context-selector" 
// unhandled import: DistributiveOmit from "@fluentui/react-utilities" 
// unhandled import: End from "@fluentui/keyboard-keys" 
// unhandled import: Enter from "@fluentui/keyboard-keys" 
// unhandled import: ExtractSlotProps from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Home from "@fluentui/keyboard-keys" 
// unhandled import: Radio from "@fluentui/react-radio" 
// unhandled import: RadioProps from "@fluentui/react-radio" 
// unhandled import: SelectionMode as SelectionMode_2 from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp65 {
    companion object {
        @seskar.js.JsValue("subtle")
        val subtle: Temp65

        @seskar.js.JsValue("subtle-alpha")
        val subtleAlpha: Temp65

        @seskar.js.JsValue("transparent")
        val transparent: Temp65
    }
}
