// Generated by Karakum - do not modify it manually!

package fluentui

import react.ReactNode

// unhandled import: DispatchWithoutAction from "react" 


sealed external interface Temp4 {
    var children: ReactNode
}
