// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Label from "@fluentui/react-label" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp56 {
    companion object {
        @seskar.js.JsValue("medium")
        val medium: Temp56

        @seskar.js.JsValue("large")
        val large: Temp56
    }
}
