// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


sealed external interface Temp173 : CardProps {
    /**
     * Represents a card that contains interactive events (MouseEvents) or is a button/a tag.
     *
     * @default false
     */
    var interactive: Boolean

    /**
     * Represents a selectable card.
     *
     * @default false
     */
    var selectable: Boolean

    /**
     * Defines whether the card is currently selected.
     *
     * @default false
     */
    override var selected: Boolean?

    /**
     * Defines whether the card internal checkbox is currently focused.
     *
     * @default false
     */
    var selectFocused: Boolean
}
