// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ARIAButtonSlotProps from "@fluentui/react-aria" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp51 {
    companion object {
        @seskar.js.JsValue("rounded")
        val rounded: Temp51

        @seskar.js.JsValue("circular")
        val circular: Temp51

        @seskar.js.JsValue("square")
        val square: Temp51
    }
}
