// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ARIAButtonResultProps from "@fluentui/react-aria" 
// unhandled import: ARIAButtonType from "@fluentui/react-aria" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ContextSelector from "@fluentui/react-context-selector" 
// unhandled import: FC from "react" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: JSXElementConstructor from "react" 
// unhandled import: PortalProps from "@fluentui/react-portal" 
// unhandled import: PositioningShorthand from "@fluentui/react-positioning" 
// unhandled import: PositioningVirtualElement from "@fluentui/react-positioning" 
// unhandled import: Provider from "react" 
// unhandled import: ProviderProps from "react" 
// unhandled import: ReactElement from "react" 
// unhandled import: SetVirtualMouseTarget from "@fluentui/react-positioning" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 
// unhandled import: TriggerProps from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp18 {
    companion object {
        @seskar.js.JsValue("brand")
        val brand: Temp18

        @seskar.js.JsValue("inverted")
        val inverted: Temp18
    }
}
