// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp112 {
    companion object {
        @seskar.js.JsValue("outline")
        val outline: Temp112

        @seskar.js.JsValue("underline")
        val underline: Temp112

        @seskar.js.JsValue("filled-darker")
        val filledDarker: Temp112

        @seskar.js.JsValue("filled-lighter")
        val filledLighter: Temp112
    }
}
