// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: Avatar from "@fluentui/react-avatar" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: PresenceBadge from "@fluentui/react-badge" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp125 {
    companion object {
        @seskar.js.JsValue("extra-small")
        val extraSmall: Temp125

        @seskar.js.JsValue("small")
        val small: Temp125

        @seskar.js.JsValue("medium")
        val medium: Temp125

        @seskar.js.JsValue("large")
        val large: Temp125

        @seskar.js.JsValue("extra-large")
        val extraLarge: Temp125

        @seskar.js.JsValue("huge")
        val huge: Temp125
    }
}
