// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: BackgroundAppearanceContextValue from "@fluentui/react-shared-contexts" 
// unhandled import: ComponentProps from "@fluentui/react-utilities" 
// unhandled import: ComponentState from "@fluentui/react-utilities" 
// unhandled import: ForwardRefComponent from "@fluentui/react-utilities" 
// unhandled import: Slot from "@fluentui/react-utilities" 
// unhandled import: SlotClassNames from "@fluentui/react-utilities" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp142 {
    companion object {
        @seskar.js.JsValue("button")
        val button: Temp142

        @seskar.js.JsValue("span")
        val span: Temp142
    }
}
