// Generated by Karakum - do not modify it manually!

package fluentui

// unhandled import: ContextSelector from "@fluentui/react-context-selector" 
// unhandled import: ObserveOptions from "@fluentui/priority-overflow" 
// unhandled import: OnUpdateOverflow from "@fluentui/priority-overflow" 
// unhandled import: OverflowDividerEntry from "@fluentui/priority-overflow" 
// unhandled import: OverflowGroupState from "@fluentui/priority-overflow" 
// unhandled import: OverflowItemEntry from "@fluentui/priority-overflow" 


@Suppress("NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@seskar.js.JsVirtual
sealed external interface Temp131 {
    companion object {
        @seskar.js.JsValue("registerItem")
        val registerItem: Temp131

        @seskar.js.JsValue("updateOverflow")
        val updateOverflow: Temp131

        @seskar.js.JsValue("registerOverflowMenu")
        val registerOverflowMenu: Temp131

        @seskar.js.JsValue("registerDivider")
        val registerDivider: Temp131
    }
}
